# -*- coding: utf-8 -*-
"""Untitled40.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zcc06emE3ehHJxSpbixgDoc82eJmhylh
"""

# ================================================================
#             NLP TEXT ANALYZER MINI PROJECT
# NLTK + SciPy + Gensim + Pattern + TextBlob
#                 GOOGLE COLAB
# ================================================================

# ================================================================
# 1. INSTALL REQUIRED LIBRARIES
# ================================================================

!pip install -q nltk scipy gensim textblob

# ================================================================
# 2. IMPORT LIBRARIES
# ================================================================

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import scipy
import scipy.linalg

import nltk

# Fix possible Gensim/SciPy compatibility issue
if not hasattr(scipy.linalg, "triu"):
    scipy.linalg.triu = np.triu

from gensim.models import Word2Vec

from nltk.tokenize import word_tokenize, sent_tokenize
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
from nltk.probability import FreqDist

from textblob import TextBlob

from scipy.spatial.distance import cosine

# ================================================================
# 3. DOWNLOAD NLTK DATA
# ================================================================

nltk.download("punkt", quiet=True)
nltk.download("punkt_tab", quiet=True)
nltk.download("stopwords", quiet=True)
nltk.download("wordnet", quiet=True)
nltk.download("omw-1.4", quiet=True)

print("=" * 70)
print("              NLP TEXT ANALYZER MINI PROJECT")
print("=" * 70)

# ================================================================
# 4. USER INPUT
# ================================================================

print("\nEnter a paragraph for NLP analysis.")

text = input("\nYour text: ")

# Default text
if not text.strip():
    text = """
    Artificial intelligence is changing the world rapidly.
    Natural Language Processing helps computers understand human language.
    NLP is used in chatbots, sentiment analysis, machine translation,
    search engines and recommendation systems.
    I really enjoy learning NLP because it is useful and interesting.
    """

print("\nINPUT TEXT")
print("-" * 70)
print(text)

# ================================================================
# 5. NLTK IMPLEMENTATION
# ================================================================

print("\n" + "=" * 70)
print("1. NLTK IMPLEMENTATION")
print("=" * 70)

# Sentence tokenization
sentences = sent_tokenize(text)

# Word tokenization
tokens = word_tokenize(text)

print("\nNumber of sentences:", len(sentences))
print("Number of tokens   :", len(tokens))

# Convert to lowercase and keep alphabetic words
clean_words = [
    word.lower()
    for word in tokens
    if word.isalpha()
]

# Stopword removal
stop_words = set(stopwords.words("english"))

filtered_words = [
    word
    for word in clean_words
    if word not in stop_words
]

# Lemmatization
lemmatizer = WordNetLemmatizer()

lemmatized_words = [
    lemmatizer.lemmatize(word)
    for word in filtered_words
]

print("\nAfter Stopword Removal:")
print(filtered_words)

print("\nAfter Lemmatization:")
print(lemmatized_words)

# Word frequency
frequency = FreqDist(lemmatized_words)

top_words = frequency.most_common(10)

print("\nTOP 10 WORDS")
print("-" * 50)

for word, count in top_words:
    print(f"{word:20} -> {count}")

# Graph: Word frequency
if top_words:

    words = [x[0] for x in top_words]
    counts = [x[1] for x in top_words]

    plt.figure(figsize=(10, 5))
    plt.bar(words, counts)
    plt.xlabel("Words")
    plt.ylabel("Frequency")
    plt.title("NLTK - Top 10 Word Frequencies")
    plt.xticks(rotation=45)
    plt.tight_layout()
    plt.show()

# ================================================================
# 6. PATTERN IMPLEMENTATION
# ================================================================

print("\n" + "=" * 70)
print("2. PATTERN IMPLEMENTATION")
print("=" * 70)

print("""
Pattern3 cannot be imported reliably in the current Colab
Python 3.12 environment because the package is outdated.

The Pattern sentiment analyzer is used through TextBlob.
This section demonstrates the Pattern-based sentiment component.
""")

pattern_text = TextBlob(text)

pattern_polarity = pattern_text.sentiment.polarity
pattern_subjectivity = pattern_text.sentiment.subjectivity

if pattern_polarity > 0:
    pattern_sentiment = "Positive"
elif pattern_polarity < 0:
    pattern_sentiment = "Negative"
else:
    pattern_sentiment = "Neutral"

print("Pattern-based NLP analysis")
print("-" * 50)
print("Polarity     :", round(pattern_polarity, 4))
print("Subjectivity :", round(pattern_subjectivity, 4))
print("Sentiment    :", pattern_sentiment)

# ================================================================
# 7. TEXTBLOB IMPLEMENTATION
# ================================================================

print("\n" + "=" * 70)
print("3. TEXTBLOB IMPLEMENTATION")
print("=" * 70)

blob = TextBlob(text)

polarity = blob.sentiment.polarity
subjectivity = blob.sentiment.subjectivity

if polarity > 0:
    sentiment = "Positive"
elif polarity < 0:
    sentiment = "Negative"
else:
    sentiment = "Neutral"

print("Polarity     :", round(polarity, 4))
print("Subjectivity :", round(subjectivity, 4))
print("Sentiment    :", sentiment)

# Sentence-level sentiment
sentence_results = []

for sentence in blob.sentences:

    p = sentence.sentiment.polarity

    if p > 0:
        s = "Positive"
    elif p < 0:
        s = "Negative"
    else:
        s = "Neutral"

    sentence_results.append(
        [str(sentence), round(p, 4), s]
    )

sentence_df = pd.DataFrame(
    sentence_results,
    columns=["Sentence", "Polarity", "Sentiment"]
)

print("\nSENTENCE-LEVEL SENTIMENT")
print("-" * 70)
print(sentence_df.to_string(index=False))

# Graph: Sentiment
plt.figure(figsize=(7, 5))

plt.bar(
    ["Polarity", "Subjectivity"],
    [polarity, subjectivity]
)

plt.xlabel("Measure")
plt.ylabel("Score")
plt.title("TextBlob Sentiment Analysis")
plt.ylim(-1, 1)

plt.tight_layout()
plt.show()

# ================================================================
# 8. GENSIM IMPLEMENTATION
# ================================================================

print("\n" + "=" * 70)
print("4. GENSIM IMPLEMENTATION")
print("=" * 70)

training_sentences = []

for sentence in sentences:

    words = word_tokenize(sentence.lower())

    words = [
        word
        for word in words
        if word.isalpha() and word not in stop_words
    ]

    if len(words) >= 2:
        training_sentences.append(words)

print("\nTraining data:")

for sentence in training_sentences:
    print(sentence)

# Word2Vec model
model = Word2Vec(
    sentences=training_sentences,
    vector_size=50,
    window=3,
    min_count=1,
    workers=2,
    epochs=100,
    seed=42
)

vocabulary = list(model.wv.index_to_key)

print("\nWord2Vec model trained successfully!")
print("Vocabulary size:", len(vocabulary))

print("\nVocabulary:")
print(vocabulary)

# Sample word vectors
print("\nSAMPLE WORD VECTORS")

for word in vocabulary[:5]:

    print("\nWord:", word)
    print("Vector:", model.wv[word][:10])

# Similar words
if len(vocabulary) >= 3:

    selected_word = vocabulary[0]

    print("\nSIMILAR WORDS TO:", selected_word)

    similar_words = model.wv.most_similar(
        selected_word,
        topn=min(5, len(vocabulary) - 1)
    )

    for word, score in similar_words:
        print(f"{word:20} -> {score:.4f}")

# ================================================================
# 9. SCIPY IMPLEMENTATION
# ================================================================

print("\n" + "=" * 70)
print("5. SCIPY IMPLEMENTATION")
print("=" * 70)

if len(vocabulary) >= 2:

    word1 = vocabulary[0]
    word2 = vocabulary[1]

    vector1 = model.wv[word1]
    vector2 = model.wv[word2]

    cosine_distance = cosine(vector1, vector2)

    cosine_similarity = 1 - cosine_distance

    print("\nWord 1            :", word1)
    print("Word 2            :", word2)
    print("Cosine Distance   :", round(cosine_distance, 4))
    print("Cosine Similarity :", round(cosine_similarity, 4))

else:

    cosine_similarity = None

    print("Not enough vocabulary for similarity.")

# ================================================================
# 10. SCIPY + GENSIM SIMILARITY MATRIX
# ================================================================

print("\n" + "=" * 70)
print("SCIPY + GENSIM WORD SIMILARITY MATRIX")
print("=" * 70)

selected_words = vocabulary[:min(8, len(vocabulary))]

if len(selected_words) >= 2:

    matrix = []

    for word_a in selected_words:

        row = []

        for word_b in selected_words:

            vec_a = model.wv[word_a]
            vec_b = model.wv[word_b]

            distance = cosine(vec_a, vec_b)

            similarity_score = 1 - distance

            row.append(similarity_score)

        matrix.append(row)

    similarity_df = pd.DataFrame(
        matrix,
        index=selected_words,
        columns=selected_words
    )

    print("\nSimilarity Matrix:")
    print(similarity_df.round(3))

    # Heatmap-style graph
    plt.figure(figsize=(9, 7))

    plt.imshow(
        similarity_df.values,
        aspect="auto"
    )

    plt.colorbar(label="Cosine Similarity")

    plt.xticks(
        range(len(selected_words)),
        selected_words,
        rotation=45,
        ha="right"
    )

    plt.yticks(
        range(len(selected_words)),
        selected_words
    )

    plt.title("Gensim Word2Vec + SciPy Similarity")

    plt.tight_layout()
    plt.show()

# ================================================================
# 11. FINAL PROJECT REPORT
# ================================================================

print("\n" + "=" * 70)
print("                  FINAL PROJECT REPORT")
print("=" * 70)

print("\nPROJECT TITLE")
print("-" * 70)
print("NLP Text Analyzer using NLTK, SciPy, Gensim, Pattern and TextBlob")

print("\nTEXT STATISTICS")
print("-" * 70)

print("Number of sentences       :", len(sentences))
print("Total words               :", len(clean_words))
print("Unique words              :", len(set(clean_words)))
print("Words after preprocessing :", len(lemmatized_words))

print("\nNLTK")
print("-" * 70)
print("Tokenization              : Completed")
print("Stopword removal          : Completed")
print("Lemmatization             : Completed")
print("Frequency analysis        : Completed")

print("\nPATTERN")
print("-" * 70)
print("Pattern-based analysis    : Completed")
print("Polarity                  :", round(pattern_polarity, 4))
print("Subjectivity              :", round(pattern_subjectivity, 4))
print("Sentiment                 :", pattern_sentiment)

print("\nTEXTBLOB")
print("-" * 70)
print("Sentiment analysis        : Completed")
print("Polarity                  :", round(polarity, 4))
print("Subjectivity              :", round(subjectivity, 4))
print("Overall sentiment         :", sentiment)

print("\nGENSIM")
print("-" * 70)
print("Word2Vec                  : Completed")
print("Vocabulary size           :", len(vocabulary))

print("\nSCIPY")
print("-" * 70)

if cosine_similarity is not None:
    print("Cosine similarity         :", round(cosine_similarity, 4))
else:
    print("Cosine similarity         : Not available")

print("\nCONCLUSION")
print("-" * 70)

print(
    "The NLP Text Analyzer successfully demonstrates natural "
    "language processing techniques using multiple libraries. "
    "NLTK was used for preprocessing and frequency analysis, "
    "Pattern-based functionality was used for sentiment analysis, "
    "TextBlob was used for sentiment and subjectivity, Gensim "
    "was used to generate Word2Vec embeddings, and SciPy was "
    "used to calculate cosine similarity between word vectors."
)

print("\n" + "=" * 70)
print("                    PROJECT COMPLETED")
print("=" * 70)t